name: IntelligentLifeInsurance
favicon: null
layout_spectrum: 0.90667
typography_spectrum: 0.92127
title: Intelligent Life Insurance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f2db'
    - '#67b8a7'
    - '#114f82'
    - '#01013f'
    - '#d39061'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
